SELECT
ADMIN_DIM_DATE2.FIRST_MONTH_DT,
ADMIN.DIM_GRP.GRP_ID,
ADMIN.DIM_GRP.GRP_NM,
-- define PROGRAM, based on GROUP ID values
CASE
WHEN ADMIN.DIM_GRP.GRP_ID IN (9016179,9016178,9016161,9016181,9016180,9016162,9016203,9016202,9016173,9016183,9016182,9016163,9016185,9016184,9016164,9016205,9016204,9016174,9016187,9016186,9016165,9016189,9016188,9016166,9016191,9016190,9016167,9016168,9016207,9016206,9016175,9016195,9016194,9016169,9016196,9016170,9016210,9016177)
THEN 'BadgerCare Plus Standard'
WHEN ADMIN.DIM_GRP.GRP_ID IN (9016199,9032722,9032723,9032724,9016198,9032719,9032720,9032721,9016171,9032714,9032716,9032717,9016201,9016200,9016172)
THEN 'BadgerCare Plus Childless Adults'
WHEN ADMIN.DIM_GRP.GRP_ID IN (9041322,9041323,9041324)
THEN 'SSI Only'
ELSE 'NA' END AS PROGRAM,
-- define PROGRAM_GROUP, based on PROGRAM to display ALL Badgercare and ALL SSI members
CASE
WHEN PROGRAM IN ('BadgerCare Plus Standard', 'BadgerCare Plus Childless Adults') THEN 'BadgerCare Plus ALL'
WHEN PROGRAM IN ('SSI Only') THEN 'SSI ALL'
ELSE 'NA' END AS PROGRAM_GROUP,
PROD_DATAMART_UTY.ADMIN.MA_MEMBER_MONTH_T.DUAL_STATUS_NM,
SHARED_RISK_RIDER.RIDER_NM,
ADMIN.DIM_PATIENT.GENDER_NM,
-- define AGE BAND, with different bands set for each program
CASE 
WHEN PROGRAM IN ('BadgerCare Plus Standard') AND DATE_PART('YEARS',AGE(ADMIN_DIM_DATE2.FIRST_MONTH_DT,( ADMIN.DIM_PATIENT_DEMOG.PATIENT_BIRTH_DT))) <1 THEN '< 1'
WHEN PROGRAM IN ('BadgerCare Plus Standard') AND DATE_PART('YEARS',AGE(ADMIN_DIM_DATE2.FIRST_MONTH_DT,( ADMIN.DIM_PATIENT_DEMOG.PATIENT_BIRTH_DT))) BETWEEN 1 AND 14 THEN '1-14'
WHEN PROGRAM IN ('BadgerCare Plus Standard') AND DATE_PART('YEARS',AGE(ADMIN_DIM_DATE2.FIRST_MONTH_DT,( ADMIN.DIM_PATIENT_DEMOG.PATIENT_BIRTH_DT))) BETWEEN 15 AND 20 THEN '15-20'
WHEN PROGRAM IN ('BadgerCare Plus Standard') AND DATE_PART('YEARS',AGE(ADMIN_DIM_DATE2.FIRST_MONTH_DT,( ADMIN.DIM_PATIENT_DEMOG.PATIENT_BIRTH_DT))) BETWEEN 21 AND 44 THEN '21-44'
WHEN PROGRAM IN ('BadgerCare Plus Standard') AND DATE_PART('YEARS',AGE(ADMIN_DIM_DATE2.FIRST_MONTH_DT,( ADMIN.DIM_PATIENT_DEMOG.PATIENT_BIRTH_DT))) >=45 THEN '45+'
WHEN PROGRAM IN ('BadgerCare Plus Childless Adults') AND DATE_PART('YEARS',AGE(ADMIN_DIM_DATE2.FIRST_MONTH_DT,( ADMIN.DIM_PATIENT_DEMOG.PATIENT_BIRTH_DT))) BETWEEN 19 AND 44 THEN '19-44'
WHEN PROGRAM IN ('BadgerCare Plus Childless Adults') AND DATE_PART('YEARS',AGE(ADMIN_DIM_DATE2.FIRST_MONTH_DT,( ADMIN.DIM_PATIENT_DEMOG.PATIENT_BIRTH_DT))) >=45 THEN '45+'
WHEN PROGRAM IN ('SSI Only') AND DATE_PART('YEARS',AGE(ADMIN_DIM_DATE2.FIRST_MONTH_DT,( ADMIN.DIM_PATIENT_DEMOG.PATIENT_BIRTH_DT))) BETWEEN 19 AND 39 THEN '19-39'
WHEN PROGRAM IN ('SSI Only') AND DATE_PART('YEARS',AGE(ADMIN_DIM_DATE2.FIRST_MONTH_DT,( ADMIN.DIM_PATIENT_DEMOG.PATIENT_BIRTH_DT))) BETWEEN 40 AND 64 THEN '40-64'
WHEN PROGRAM IN ('SSI Only') AND DATE_PART('YEARS',AGE(ADMIN_DIM_DATE2.FIRST_MONTH_DT,( ADMIN.DIM_PATIENT_DEMOG.PATIENT_BIRTH_DT))) >= 65 THEN '65+'
ELSE 'NA' END AS AGE_BAND,
PATCUR_DIM_ADDR.STATE_ABBR,
PATCUR_DIM_ADDR.COUNTY_NM,
-- define MEDICAID_RATE_REGION, based on patient address state (WI) AND county
CASE
WHEN PATCUR_DIM_ADDR.STATE_ABBR IN ('WI') 
AND PATCUR_DIM_ADDR.COUNTY_NM IN ('ASHLAND','BARRON','BAYFIELD','BURNETT','DOUGLAS','DUNN','FOREST','IRON','LANGLADE','LINCOLN','MENOMINEE','ONEIDA','PEPIN','PIERCE','POLK','PRICE','RUSK','SAWYER','SHAWANO','ST. CROIX','TAYLOR','VILAS','WASHBURN')
THEN 'Region 1'
WHEN PATCUR_DIM_ADDR.STATE_ABBR IN ('WI') 
AND PATCUR_DIM_ADDR.COUNTY_NM IN ('FOND DU LAC','BROWN','CALUMET','DOOR','FLORENCE','KEWAUNEE','MANITOWOC','MARINETTE','OCONTO','OUTAGAMIE','SHEBOYGAN','WAUPACA','WINNEBAGO')
THEN 'Region 2'
WHEN PATCUR_DIM_ADDR.STATE_ABBR IN ('WI') 
AND PATCUR_DIM_ADDR.COUNTY_NM IN ('ADAMS','BUFFALO','CHIPPEWA','CRAWFORD','EAU CLAIRE','JACKSON','JUNEAU','LA CROSSE','MARQUETTE','MONROE','RICHLAND','TREMPEALEAU','VERNON','WOOD','CLARK','GREEN LAKE','MARATHON','PORTAGE','WAUSHARA')
THEN 'Region 3'
WHEN PATCUR_DIM_ADDR.STATE_ABBR IN ('WI') 
AND PATCUR_DIM_ADDR.COUNTY_NM IN ('COLUMBIA','DANE','DODGE','GRANT','GREEN','IOWA','JEFFERSON','LAFAYETTE','ROCK','SAUK','WALWORTH')
THEN 'Region 4'
WHEN PATCUR_DIM_ADDR.STATE_ABBR IN ('WI') 
AND PATCUR_DIM_ADDR.COUNTY_NM IN ('KENOSHA','OZAUKEE','RACINE','WASHINGTON','WAUKESHA')
THEN 'Region 5'
WHEN PATCUR_DIM_ADDR.STATE_ABBR IN ('WI') 
AND PATCUR_DIM_ADDR.COUNTY_NM IN ('MILWAUKEE')
THEN 'Region 6'
else 'NA' END AS MEDICAID_RATE_REGION,
CASE WHEN(CUR_CVG_MEM.EXPIRATION_DT <= CURRENT_DATE) THEN 'TERMED' ELSE 'ACTIVE' END AS TERM_STATUS,
CASE WHEN (CUR_CVG_MEM.EFFECTIVE_DT = ADMIN_DIM_DATE2.FIRST_MONTH_DT) THEN 'NEW ENROLLMENT' ELSE 'EXISTING ENROLLMENT' END AS ENROLLMENT_STATUS,
COUNT (DISTINCT(ADMIN.FACT_MEMBER_MONTH_LVL1.MEMBER_NBR)) AS COUNT_MEMBERS
FROM ADMIN.DIM_GRP
RIGHT OUTER JOIN ADMIN.FACT_MEMBER_MONTH_LVL1 ON (ADMIN.DIM_GRP.GRP_ID=ADMIN.FACT_MEMBER_MONTH_LVL1.GRP_ID 
AND ADMIN.DIM_GRP.SRC_SYSTM_IND=ADMIN.FACT_MEMBER_MONTH_LVL1.SRC_SYSTM_IND 
AND ADMIN.DIM_GRP.CURR_ROW_FLG = 'Y')
LEFT OUTER JOIN ADMIN.DIM_MEDICAL_PLAN ON (ADMIN.DIM_MEDICAL_PLAN.SRC_SYSTM_IND=ADMIN.FACT_MEMBER_MONTH_LVL1.SRC_SYSTM_IND 
AND ADMIN.DIM_MEDICAL_PLAN.BENEFIT_PLAN_ID=ADMIN.FACT_MEMBER_MONTH_LVL1.MEDICAL_PLAN_ID 
AND ADMIN.DIM_MEDICAL_PLAN.CURR_ROW_FLG = 'Y')
LEFT OUTER JOIN ADMIN.DIM_PAYOR ON (ADMIN.DIM_PAYOR.PAYOR_ID=ADMIN.DIM_MEDICAL_PLAN.PAYOR_ID
AND ADMIN.DIM_PAYOR.CURR_ROW_FLG = 'Y' 
AND ADMIN.DIM_PAYOR.SRC_SYSTM_IND = 'EPIC')
LEFT OUTER JOIN ADMIN.DIM_COVERAGE ON (ADMIN.FACT_MEMBER_MONTH_LVL1.COVERAGE_ID=ADMIN.DIM_COVERAGE.COVERAGE_ID 
AND ADMIN.FACT_MEMBER_MONTH_LVL1.SRC_SYSTM_IND = ADMIN.DIM_COVERAGE.SRC_SYSTM_IND
AND ADMIN.DIM_COVERAGE.CURR_ROW_FLG = 'Y')
LEFT OUTER JOIN ADMIN.DIM_PATIENT ON (ADMIN.FACT_MEMBER_MONTH_LVL1.PATIENT_ID=ADMIN.DIM_PATIENT.PATIENT_ID
AND ADMIN.FACT_MEMBER_MONTH_LVL1.SRC_SYSTM_IND=ADMIN.DIM_PATIENT.SRC_SYSTM_IND
AND ADMIN.DIM_PATIENT.CURR_ROW_FLG = 'Y'
AND ADMIN.DIM_PATIENT.CURR_ROW_FLG='Y')
LEFT OUTER JOIN ADMIN.XREF_PATIENT_ADDR ON (ADMIN.XREF_PATIENT_ADDR.ADDR_TYPE_CD=1
AND ADMIN.XREF_PATIENT_ADDR.MASTER_PATIENT_KEY=ADMIN.DIM_PATIENT.MASTER_PATIENT_KEY
AND ADMIN.XREF_PATIENT_ADDR.ADDR_TYPE_CD = '1'
AND ADMIN.XREF_PATIENT_ADDR.CURR_ROW_FLG = 'Y'
AND ADMIN.DIM_PATIENT.CURR_ROW_FLG='Y')
LEFT OUTER JOIN ADMIN.DIM_ADDR PATCUR_DIM_ADDR ON (ADMIN.XREF_PATIENT_ADDR.ADDR_TYPE_CD=1
AND PATCUR_DIM_ADDR.ADDR_KEY=ADMIN.XREF_PATIENT_ADDR.ADDR_KEY)
LEFT OUTER JOIN ADMIN.DIM_PATIENT_DEMOG ON (ADMIN.DIM_PATIENT.MASTER_PATIENT_KEY=ADMIN.DIM_PATIENT_DEMOG.MASTER_PATIENT_KEY
AND ADMIN.DIM_PATIENT_DEMOG.CURR_ROW_FLG = 'Y'
AND ADMIN.DIM_PATIENT.CURR_ROW_FLG='Y')
LEFT OUTER JOIN ( 
SELECT
A.EFFECTIVE_DT_KEY, 
A.EXPIRATION_DT_KEY, 
A.COVERAGE_KEY,
A.SUBSCRIBER_PATIENT_KEY, 
A.MASTER_PATIENT_KEY, 
A.MASTER_COVERAGE_KEY,
A.PATIENT_KEY, 
A.GRP_KEY, 
A.MEMBER_LIST_CD_KEY, 
A.TERMINATION_REASON_KEY, 
A.EFFECTIVE_DT, 
A.EXPIRATION_DT, 
A.COVERAGE_ID, 
A.SUBSCRIBER_PATIENT_ID, 
A.PATIENT_ID, 
A.GRP_ID, 
A.TERMINATION_REASON_CD, 
A.LINE, 
A.MEMBER_NBR,
A.SUBSCRIBER_FLG, 
A.MEMBER_COVERED_FLG, 
A.DELETE_ROW_FLG, 
A.POST_TM,
A.MEMBER_ID_FROM_FILE,
A.SRC_SYSTM_IND
FROM AXT123.FACT_COVERAGE_MEMBER A 
WHERE A.UNTY_ACTIVE_FLG = 'Y' 
AND A.DELETE_ROW_FLG = 'N'
) CUR_CVG_MEM
ON (CUR_CVG_MEM.DELETE_ROW_FLG= 'N'
AND ADMIN.FACT_MEMBER_MONTH_LVL1.PATIENT_ID=CUR_CVG_MEM.PATIENT_ID 
AND ADMIN.FACT_MEMBER_MONTH_LVL1.COVERAGE_ID=CUR_CVG_MEM.COVERAGE_ID 
AND ADMIN.FACT_MEMBER_MONTH_LVL1.SRC_SYSTM_IND=CUR_CVG_MEM.SRC_SYSTM_IND)
LEFT OUTER JOIN ADMIN.DIM_DATE ADMIN_DIM_DATE2 ON (ADMIN_DIM_DATE2.ACTUAL_DT=ADMIN.FACT_MEMBER_MONTH_LVL1.CALCULATED_INTERVAL_DT)
LEFT OUTER JOIN ADMIN.DIM_RIDER SHARED_RISK_RIDER ON (SHARED_RISK_RIDER.RIDER_TYPE_CD='5'
AND SHARED_RISK_RIDER.RIDER_KEY=ADMIN.FACT_MEMBER_MONTH_LVL1.RISK_RIDER_KEY)
LEFT OUTER JOIN PROD_DATAMART_UTY.ADMIN.MA_MEMBER_MONTH_T ON (PROD_DATAMART_UTY.ADMIN.MA_MEMBER_MONTH_T.MASTER_COVERAGE_KEY=ADMIN.FACT_MEMBER_MONTH_LVL1.MASTER_COVERAGE_KEY 
AND DATE_TRUNC('MONTH', ADMIN.FACT_MEMBER_MONTH_LVL1.CALCULATED_INTERVAL_DT) =PROD_DATAMART_UTY.ADMIN.MA_MEMBER_MONTH_T.CALCULATED_INTERVAL_DT 
AND PROD_DATAMART_UTY.ADMIN.MA_MEMBER_MONTH_T.SRC_SYSTM_IND = 'MP')
WHERE(
(ADMIN.FACT_MEMBER_MONTH_LVL1.CALCULATED_INTERVAL_NBR = 15)
-- 9000000 AND 9000001 are for Medicaid, 9000041 is for SSI
AND ADMIN.DIM_MEDICAL_PLAN.LOB_CD IN (9000000, 9000001, 9000041)
-- use a 3 year lookback window
AND YEAR(ADMIN_DIM_DATE2.FIRST_MONTH_DT) >= YEAR(CURRENT_DATE) - 3
AND ADMIN_DIM_DATE2.FIRST_MONTH_DT <= CURRENT_DATE
AND(NVL(ADMIN.DIM_PAYOR.REPORT_GRP_6_CD, '*') IN ('*','1','2','3','4','5'))
AND(ADMIN.DIM_PATIENT.CURR_ROW_FLG='Y')
)
GROUP BY
ADMIN_DIM_DATE2.FIRST_MONTH_DT,
ADMIN.DIM_GRP.GRP_ID,
ADMIN.DIM_GRP.GRP_NM,
PROGRAM,
PROGRAM_GROUP,
PROD_DATAMART_UTY.ADMIN.MA_MEMBER_MONTH_T.DUAL_STATUS_NM,
SHARED_RISK_RIDER.RIDER_NM,
ADMIN.DIM_PATIENT.GENDER_NM,
AGE_BAND,
PATCUR_DIM_ADDR.STATE_ABBR,
PATCUR_DIM_ADDR.COUNTY_NM,
MEDICAID_RATE_REGION,
TERM_STATUS,
ENROLLMENT_STATUS
ORDER BY
ADMIN_DIM_DATE2.FIRST_MONTH_DT,
PROGRAM,
MEDICAID_RATE_REGION,
TERM_STATUS,
ENROLLMENT_STATUS;